name: Laravel Pint
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@2.2.0
        with:
          verboseMode: true
