name: Laravel Pint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_code_styling:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Pint for code styling
        uses: aglipanci/laravel-pint-action@2.3.0

      - name: Auto-commit style fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Chore: Fix styling"
